# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uygulama_rezervasyon.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow4(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 991, 781))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../arka plan.jpg"))
        self.label.setObjectName("label")
        self.tblrezervasyon = QtWidgets.QTableWidget(self.centralwidget)
        self.tblrezervasyon.setGeometry(QtCore.QRect(250, 380, 731, 261))
        self.tblrezervasyon.setRowCount(50)
        self.tblrezervasyon.setColumnCount(6)
        self.tblrezervasyon.setObjectName("tblrezervasyon")
        self.pbanaekran = QtWidgets.QPushButton(self.centralwidget)
        self.pbanaekran.setGeometry(QtCore.QRect(890, 670, 91, 31))
        self.pbanaekran.setObjectName("pbanaekran")
        self.lnID = QtWidgets.QLabel(self.centralwidget)
        self.lnID.setGeometry(QtCore.QRect(20, 410, 68, 19))
        self.lnID.setObjectName("lnID")
        self.lnOda = QtWidgets.QLabel(self.centralwidget)
        self.lnOda.setGeometry(QtCore.QRect(20, 460, 68, 19))
        self.lnOda.setObjectName("lnOda")
        self.lneID = QtWidgets.QLineEdit(self.centralwidget)
        self.lneID.setGeometry(QtCore.QRect(110, 410, 113, 25))
        self.lneID.setObjectName("lneID")
        self.lneOda = QtWidgets.QLineEdit(self.centralwidget)
        self.lneOda.setGeometry(QtCore.QRect(110, 460, 113, 25))
        self.lneOda.setObjectName("lneOda")
        self.pbkaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pbkaydet.setGeometry(QtCore.QRect(20, 580, 88, 27))
        self.pbkaydet.setObjectName("pbkaydet")
        self.pbsil = QtWidgets.QPushButton(self.centralwidget)
        self.pbsil.setGeometry(QtCore.QRect(130, 580, 88, 27))
        self.pbsil.setObjectName("pbsil")
        self.pblistele = QtWidgets.QPushButton(self.centralwidget)
        self.pblistele.setGeometry(QtCore.QRect(20, 630, 88, 27))
        self.pblistele.setObjectName("pblistele")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 380, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lneisimsoyisim = QtWidgets.QLineEdit(self.centralwidget)
        self.lneisimsoyisim.setGeometry(QtCore.QRect(110, 381, 111, 21))
        self.lneisimsoyisim.setObjectName("lneisimsoyisim")
        self.giris_tarihi = QtWidgets.QDateEdit(self.centralwidget)
        self.giris_tarihi.setGeometry(QtCore.QRect(110, 500, 110, 22))
        self.giris_tarihi.setMouseTracking(False)
        self.giris_tarihi.setDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime(0, 0, 0)))
        self.giris_tarihi.setCalendarPopup(True)
        self.giris_tarihi.setObjectName("giris_tarihi")
        self.cikis_tarihi = QtWidgets.QDateEdit(self.centralwidget)
        self.cikis_tarihi.setGeometry(QtCore.QRect(110, 530, 110, 22))
        self.cikis_tarihi.setDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime(0, 0, 0)))
        self.cikis_tarihi.setCalendarPopup(True)
        self.cikis_tarihi.setObjectName("cikis_tarihi")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 500, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 530, 71, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbanaekran.setText(_translate("MainWindow", "Ana Ekran"))
        self.lnID.setText(_translate("MainWindow", "ID"))
        self.lnOda.setText(_translate("MainWindow", "Oda No"))
        self.pbkaydet.setText(_translate("MainWindow", "Kaydet"))
        self.pbsil.setText(_translate("MainWindow", "Sil"))
        self.pblistele.setText(_translate("MainWindow", "Listele"))
        self.label_2.setText(_translate("MainWindow", "İsim Soyisim"))
        self.label_3.setText(_translate("MainWindow", "Giriş Tarihi"))
        self.label_4.setText(_translate("MainWindow", "Çıkış Tarihi"))

